### ISSUE TITLE
Missing elsif for https:youtu.be url

### ISSUE THREAD

**Issue by charleswroy** [perlancar/perl-YouTube-Util#1]
Greetings,

First of all, thank you for your module.

It seems that this type of link is not being detected by the module: https://youtu.be/FdeioVndUhs

See : https://youtube.googleblog.com/2009/12/make-way-for-youtube-links.html

I've hacked this modification : 
`    } elsif ( $arg =~ m!\Ahttps?://youtu.be! && $arg =~ /($re)(?:&|\#|\z)/ ) {
`

In this sub:
```
sub extract_youtube_video_id {
    my $arg = shift;

    my $re = $Regexp::Pattern::YouTube::RE{video_id}{pat};
    if ($arg =~ /\A$re\z/) {
        return $arg;
    } elsif ($arg =~ m!\Ahttps?://.+/embed/! &&
                 $arg =~ m!/embed/($re)(?:\?|\#|\z)!) {
        return $1;
    } elsif ($arg =~ m!\Ahttps?://! &&
                 $arg =~ /=($re)(?:&|\#|\z)/) {
        return $1;
    } elsif ( $arg =~ m!\Ahttps?://youtu.be! && $arg =~ /($re)(?:&|\#|\z)/ ) {
        return $1;
    } else {
        # assume it's a filename like that generated by youtube-dl
        if ($arg =~ /-($re)(?:\.\w+)+(?:\s|\z)/) {
            return $1;
        }
    }
    undef;
}
```
I'm pretty sure my regex could be improved. 

We now have a modified module for our project. But I would much rather use yours. 

If you may include this proposition or improve on it?

Thank you,

Charles-William Roy

**Comment by perlancar** [comment]
Thanks, recognizing youtu.be links added.
